create database agdd;
use agdd;
CREATE TABLE `agdd`.`login` (
  `loginId` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `role` VARCHAR(45) NULL,
  PRIMARY KEY (`loginId`));

INSERT INTO `agdd`.`login` (`userName`, `password`, `role`) VALUES ('admin', 'admin', 'ADMIN');

CREATE TABLE `agdd`.`diseasesolution` (
  `solutionId` INT NOT NULL AUTO_INCREMENT,
  `plantName` VARCHAR(45) NULL,
  `diseaseName` VARCHAR(45) NULL,
  `videoLink` VARCHAR(45) NULL,
  `solutionDiscription` VARCHAR(45) NULL,
  PRIMARY KEY (`solutionId`));
  
  ALTER TABLE `agdd`.`diseasesolution` 
CHANGE COLUMN `solutionDiscription` `solutionDiscription` LONGTEXT NULL DEFAULT NULL ;

INSERT INTO `agdd`.`diseasesolution` (`plantName`, `diseaseName`, `videoLink`, `solutionDiscription`) VALUES ('Paddy', 'Blast Disease', 'https://www.youtube.com/watch?v=OEE1SrcR27Y', 'Plant resistant or tolerant varieties of the crop. Many crop breeding programs focus on developing varieties with resistance to blast diseasePractice crop rotation to reduce the buildup of blast disease in the soil. Avoid planting susceptible crops in the same field consecutively.Maintain proper plant spacing to ensure good air circulation. This helps reduce humidity levels, creating an environment less favorable for the growth of the blast fungus.');
INSERT INTO `agdd`.`diseasesolution` (`plantName`, `diseaseName`, `videoLink`, `solutionDiscription`) VALUES ('Paddy', 'Brown Spot', 'https://www.youtube.com/watch?v=3aL74HP0lJ0', 'Water plants at the base to keep foliage dry. Avoid overhead watering, as moisture on leaves can contribute to the development of fungal diseases like brown spot.Water plants at the base to keep foliage dry. Avoid overhead watering, as moisture on leaves can contribute to the development of fungal diseases like brown spot.Ensure proper spacing between plants to enhance air circulation. Good air flow helps reduce humidity around the plants, creating a less favorable environment for the disease.');
INSERT INTO `agdd`.`diseasesolution` (`plantName`, `diseaseName`, `videoLink`, `solutionDiscription`) VALUES ('Paddy', 'Sheath Blight', 'https://www.youtube.com/watch?v=vJuEvYMT5UM', 'Cultural Practices:');
INSERT INTO `agdd`.`diseasesolution` (`plantName`, `diseaseName`, `videoLink`, `solutionDiscription`) VALUES ('Paddy', 'Bacterial Leaf Blight', 'https://www.youtube.com/watch?v=T9xaO67nzpA', 'Copper-based Sprays:');
INSERT INTO `agdd`.`diseasesolution` (`plantName`, `diseaseName`, `videoLink`, `solutionDiscription`) VALUES ('Paddy', 'Tungro Virus', 'https://www.youtube.com/watch?v=gEZXftdXEc0', 'Use Resistant Varieties:');
INSERT INTO `agdd`.`diseasesolution` (`plantName`, `diseaseName`, `videoLink`, `solutionDiscription`) VALUES ('Coconut Tree', 'Bud Rot', 'https://www.youtube.com/watch?v=8x0Cxe6UfT4', 'Proper Ventilation:');
INSERT INTO `agdd`.`diseasesolution` (`plantName`, `diseaseName`, `videoLink`, `solutionDiscription`) VALUES ('Coconut Tree', 'Lethal Yellowing (LY) Disease', 'https://www.youtube.com/watch?v=DVOXtR8BNR8', 'Plant Resistant Varieties:');
INSERT INTO `agdd`.`diseasesolution` (`plantName`, `diseaseName`, `videoLink`, `solutionDiscription`) VALUES ('Coconut Tree', 'Ganoderma Butt Rot', 'https://www.youtube.com/watch?v=rJjiSd9wlLk', 'Early Detection:');
INSERT INTO `agdd`.`diseasesolution` (`plantName`, `diseaseName`, `videoLink`, `solutionDiscription`) VALUES ('Coconut TreeCoconut Tree', 'Leaf Spots', 'https://www.youtube.com/watch?v=_ZNaxuWkY5U', 'Prune Affected Leaves:');
INSERT INTO `agdd`.`diseasesolution` (`plantName`, `diseaseName`, `videoLink`, `solutionDiscription`) VALUES ('Coconut Tree', 'Coconut Mite Infestation', 'https://www.youtube.com/watch?v=_zi6rhUU3HQ', 'Neem Oil:');
INSERT INTO `agdd`.`diseasesolution` (`plantName`, `diseaseName`, `videoLink`, `solutionDiscription`) VALUES ('Lettuce', 'Downy Mildew', 'https://www.youtube.com/watch?v=ljxoQzyUr_U', 'Fungicides:');
INSERT INTO `agdd`.`diseasesolution` (`plantName`, `diseaseName`, `videoLink`, `solutionDiscription`) VALUES ('Lettuce', 'Lettuce Mosaic Virus', 'https://www.youtube.com/watch?v=B-wGS-WwFtE', 'Use Resistant Varieties:');
INSERT INTO `agdd`.`diseasesolution` (`plantName`, `diseaseName`, `videoLink`, `solutionDiscription`) VALUES ('Lettuce', 'Bacterial Soft Rot', 'https://www.youtube.com/watch?v=GkLbMLPgp1Q', 'Symptoms:');
INSERT INTO `agdd`.`diseasesolution` (`plantName`, `diseaseName`, `videoLink`, `solutionDiscription`) VALUES ('Lettuce', 'Botrytis', 'https://www.youtube.com/watch?v=1wa-nmAUGA8', 'Pruning and Thinning:');
INSERT INTO `agdd`.`diseasesolution` (`plantName`, `diseaseName`, `videoLink`, `solutionDiscription`) VALUES ('Lettuce', 'Sclerotinia Lettuce Drop', 'https://www.youtube.com/watch?v=qFQcQ5KwYCA', 'Crop Rotation:');
INSERT INTO `agdd`.`diseasesolution` (`plantName`, `diseaseName`, `videoLink`, `solutionDiscription`) VALUES ('Vegetables', 'Early Blight', 'https://www.youtube.com/watch?v=-q6AmTfVYpU', 'Cultural Practices:');
INSERT INTO `agdd`.`diseasesolution` (`plantName`, `diseaseName`, `videoLink`, `solutionDiscription`) VALUES ('Vegetables', 'Late Blight', 'https://www.youtube.com/watch?v=seWWOENLRKc', 'Resistant Varieties:');
INSERT INTO `agdd`.`diseasesolution` (`plantName`, `diseaseName`, `videoLink`, `solutionDiscription`) VALUES ('Vegetables', 'Downy Mildew', 'https://www.youtube.com/watch?v=_RSduW6-hZA', 'Cultural Practices:');
INSERT INTO `agdd`.`diseasesolution` (`plantName`, `diseaseName`, `videoLink`, `solutionDiscription`) VALUES ('Vegetables', 'Bacterial Spot', 'https://www.youtube.com/watch?v=9JjVSVaVD_c', 'Copper-Based Sprays:');
INSERT INTO `agdd`.`diseasesolution` (`plantName`, `diseaseName`, `videoLink`, `solutionDiscription`) VALUES ('Vegetables', 'Alternaria Leaf Blight', 'https://www.youtube.com/shorts/q_Eg1Y9szL0', 'Fungicides:');

UPDATE `agdd`.`diseasesolution` SET `solutionDiscription` = 'Proper Water Management: Ensure well-drained soil and avoid over-irrigation, as Sheath Blight thrives in moist conditions.' WHERE (`solutionId` = '3');
UPDATE `agdd`.`diseasesolution` SET `solutionDiscription` = 'Rotate crops to break the disease cycle.Remove and destroy infected plant material.Keep the field clean to reduce the source of infection.Practice proper water management to avoid prolonged leaf wetness.Plant rice varieties that are resistant to Bacterial Leaf Blight.' WHERE (`solutionId` = '4');
UPDATE `agdd`.`diseasesolution` SET `solutionDiscription` = 'Planting Tungro-resistant rice varieties can be an effective way to manage the disease. Consult with local agricultural extension services or research institutions to identify suitable resistant varieties.Planting rice early in the season can help reduce the incidence of Tungro Virus. Early planting helps avoid the peak period of vector activity.' WHERE (`solutionId` = '5');
UPDATE `agdd`.`diseasesolution` SET `solutionDiscription` = 'Remove affected parts of the plant using clean, sharp tools. Make sure to cut well below the infected area to prevent the spread of the disease.Ensure good ventilation around the plant to reduce humidity. Increase spacing between plants if they are crowded.Bud rot is often associated with excessive moisture. Avoid overwatering and allow the soil to dry out between waterings. Use well-draining soil.' WHERE (`solutionId` = '6');
UPDATE `agdd`.`diseasesolution` SET `solutionDiscription` = 'Consider planting palm varieties that are resistant to Lethal Yellowing Disease, if available.Lethal Yellowing Disease is often transmitted by plant-sucking insects called planthoppers. Implementing control measures for these vectors can help manage the spread of the disease.Infected palms should be promptly identified and removed to prevent the disease from spreading to healthy palms.' WHERE (`solutionId` = '7');
UPDATE `agdd`.`diseasesolution` SET `solutionDiscription` = 'Avoid causing wounds to the trunk and roots during planting or other activities.Plant trees in well-drained soil to reduce the risk of waterlogged conditions.Regularly inspect trees for any signs of decay, wilting, or other symptoms.Look for conks (shelf-like structures) growing on the trunk or at the base of the tree.' WHERE (`solutionId` = '8');
UPDATE `agdd`.`diseasesolution` SET `solutionDiscription` = 'Identify the specific type of leaf spots and the affected plant species. This information is crucial for selecting the most effective solution.Remove and destroy severely infected leaves. This helps reduce the spread of pathogens to healthy parts of the plant.Ensure good air circulation around the plants. Proper spacing and pruning can help reduce humidity, which discourages fungal growth.' WHERE (`solutionId` = '9');
UPDATE `agdd`.`diseasesolution` SET `solutionDiscription` = 'Pruning: Regularly prune and remove affected leaves, stems, or fronds to reduce mite populations.Maintain Plant Health: Ensure proper irrigation, fertilization, and overall plant health to enhance the coconut tree\'s ability to resist mite infestations.redatory Mites: Introduce predatory mites that feed on coconut mites, such as Neoseiulus paspalivorus or Phytoseiulus persimilis.' WHERE (`solutionId` = '10');
UPDATE `agdd`.`diseasesolution` SET `solutionDiscription` = 'Spacing: Provide adequate spacing between plants to ensure proper air circulation.Watering: Water the plants at the base to keep foliage dry. Avoid overhead watering.Morning Watering: If possible, water early in the morning to allow the plant foliage to dry during the day.' WHERE (`solutionId` = '11');
UPDATE `agdd`.`diseasesolution` SET `solutionDiscription` = 'Choose lettuce varieties that are resistant to Lettuce Mosaic Virus. Resistant varieties can help reduce the risk of infection.Practice crop rotation by avoiding planting lettuce in the same location consecutively. This can help break the disease cycle and reduce the buildup of the virus in the soil.Aphids are vectors that can transmit Lettuce Mosaic Virus. Implement control measures to manage aphid populations, such as using insecticidal soaps or neem oil.' WHERE (`solutionId` = '12');
UPDATE `agdd`.`diseasesolution` SET `solutionDiscription` = 'Practice good sanitation in the garden or agricultural area.Remove and destroy infected plant material promptly to prevent the spread of bacteria.Avoid overwatering, as excess moisture can create favorable conditions for bacterial growth.' WHERE (`solutionId` = '13');
UPDATE `agdd`.`diseasesolution` SET `solutionDiscription` = 'Prune affected plant parts to improve air circulation, reducing humidity around the plants. This helps prevent the favorable conditions for Botrytis development.Remove and dispose of any infected plant material promptly. This includes dead leaves, flowers, or fruit that show signs of the disease.Avoid overwatering, as excess moisture can contribute to the development of Botrytis. Water the plants at the base to keep the foliage dry.' WHERE (`solutionId` = '14');
UPDATE `agdd`.`diseasesolution` SET `solutionDiscription` = 'Rotate lettuce crops with non-host crops to reduce the buildup of the pathogen in the soil.Plant lettuce varieties that are resistant or tolerant to Sclerotinia Lettuce Drop.Practice good sanitation by removing and destroying infected plant debris to prevent the spread of the fungus.Avoid overwatering and ensure proper irrigation practices to reduce humidity around the plants, which can create favorable conditions for the disease.' WHERE (`solutionId` = '15');
UPDATE `agdd`.`diseasesolution` SET `solutionDiscription` = 'Apply fungicides containing copper or other recommended fungicides. Follow the manufacturer\'s instructions for application rates and timing.Properly prune and stake plants to improve air circulation. This helps reduce humidity around the plants, creating an unfavorable environment for the fungus.Apply organic mulch around the base of plants to prevent soil splashing, which can carry fungal spores to the lower leaves.' WHERE (`solutionId` = '16');
UPDATE `agdd`.`diseasesolution` SET `solutionDiscription` = 'Plant potato and tomato varieties that are resistant to Late Blight. Resistant varieties can significantly reduce the risk of infection.Practice crop rotation to reduce the buildup of the pathogen in the soil. Avoid planting potatoes and tomatoes in the same location year after year.pply fungicides preventatively, especially during periods of high disease pressure. Copper-based fungicides and systemic fungicides may be effective.' WHERE (`solutionId` = '17');
UPDATE `agdd`.`diseasesolution` SET `solutionDiscription` = 'Apply fungicides that are effective against Downy Mildew. Consult with local agricultural extension services or experts for recommended fungicides and application schedules.Avoid overwatering, as excessive moisture can contribute to the development of Downy Mildew. Use drip irrigation or soaker hoses to keep foliage dry.Ensure proper spacing between plants to promote air circulation. This helps reduce humidity around the plants, making it less favorable for Downy Mildew.' WHERE (`solutionId` = '18');
UPDATE `agdd`.`diseasesolution` SET `solutionDiscription` = 'Resistant Varieties: Choose plant varieties that are resistant to Bacterial Spot when available.Crop Rotation: Rotate crops to reduce the buildup of the pathogen in the soil.Sanitation: Practice good garden hygiene by removing and destroying infected plant debris.Proper Spacing: Ensure proper spacing between plants for good air circulation, which can help reduce humidity and minimize disease spread.' WHERE (`solutionId` = '19');
UPDATE `agdd`.`diseasesolution` SET `solutionDiscription` = 'Remove and destroy any affected leaves as soon as you notice symptoms. This helps prevent the spread of the disease.Water the plants at the base and avoid overhead watering. Water early in the day to allow the foliage to dry quickly, reducing the conditions favorable for fungal growth.Ensure good air circulation around plants by proper spacing and pruning. This reduces the humidity around the plants, making it less conducive for the fungus.' WHERE (`solutionId` = '20');

UPDATE `agdd`.`diseasesolution` SET `videoLink` = 'https://www.youtube.com/watch?v=-q6AmTfVYpU' WHERE (`solutionId` = '20');
